version: '3.8'

services:
  homelab-hub:
    build: .
    container_name: homeserver-hub
    hostname: homeserver
    ports:
      - "8070:8000"
    volumes:
      - /opt/server-allocator/config.json:/app/config.json
    restart: unless-stopped